development:
  adapter: postgresql
  encoding: unicode
  database: <%= File.basename(Rails.root) %>_development_Amy
  pool: 5
  host: localhost
  username:  <%= ENV['PG_USERNAME'] %>
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: <%= File.basename(Rails.root) %>_test_Amy
  pool: 5
  host: localhost
  username: <%= ENV['PG_USERNAME'] %>
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: <%= File.basename(Rails.root) %>_production_Amy
  pool: 5
  username: <%= ENV['PG_USERNAME'] %>
  password: